model:
  base_learning_rate: 2.0e-6
  target: encdiff_with_mi.EncDiffWithMI
  params:
    mi_weight: 0.15
    prior_weight: 0.01
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 16
    channels: 3
    cond_stage_trainable: true
    concat_mode: False
    scale_by_std: True
    monitor: 'train/epoch_num'
    conditioning_key: crossattn
    eval_name: shapes3d

    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel_enc.UNetModel
      params:
        image_size: 16
        in_channels: 3
        out_channels: 3
        model_channels: 64
        attention_resolutions: [ 1, 2, 4]
        num_res_blocks: 2
        channel_mult: [ 1,2,4,4 ]
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: True
        context_dim: 16
        latent_unit: 20

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 2048
        monitor: "val/rec_loss"
        ckpt_path: "models/vqvae/shapes3d_vqvae.ckpt"  # Path to pre-trained VQ-VAE checkpoint
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 64
          in_channels: 3
          out_ch: 3
          ch: 32
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.diffusionmodules.openaimodel_enc.Encoder4
      params:
        d: 128
        context_dim: 16
        latent_unit: 20

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 8
    wrap: True
    train:
      target: ldm.data.disdata.Shapes3DTrain
    validation:
      target: ldm.data.disdata.Shapes3DTrain

lightning:
  callbacks:
    image_logger:
      target: main_val.ImageLogger
      params:
        log_config:
          target: ldm.tools.Record
          params:
            plot_image: true
        batch_frequency: 10000
        max_images: 8
        increase_log_steps: false
        log_images_kwargs:
          inpaint: false
          sample_swap: True
          plot_progressive_rows: False

  trainer:
    benchmark: True
    check_val_every_n_epoch: 1
    max_epochs: 15
